apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    compileSdkVersion 30
    buildToolsVersion '30.0.2'
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
    }
    buildTypes {
        release {
            consumerProguardFiles 'proguard-rules.pro'
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        exclude 'META-INF/maven/com.google.guava/guava/pom.properties'
        exclude 'META-INF/maven/com.google.guava/guava/pom.xml'
        exclude 'META-INF/maven/commons-cli/commons-cli/pom.properties'
        exclude 'META-INF/maven/commons-cli/commons-cli/pom.xml'
    }
}

dependencies {
    api project(':autopatchbase')
//    implementation 'com.meituan.robust:robust-base:1.0.0'
}

group = 'com.meituan.robust.patch'
version = '1.0.0'
// 使用 afterEvaluate 延迟 publishing 配置
afterEvaluate {
    publishing {
        publications {
            mavenJava(MavenPublication) {
                // 从 release 组件发布
                from components.release
                groupId = project.group
                artifactId = 'robust-patch' // 建议使用项目名称或更具体的名称
                version = project.version

                // (可选) 如果需要包含源码和 Javadoc
                // artifact sourceJar
                // artifact javadocJar
            }
        }
        /*repositories {
            maven {
                name = 'localRepo'
                // 使用 layout.buildDirectory 确保路径正确
                url = layout.buildDirectory.dir("repo")
            }
        }*/
    }
}