apply from: 'config.gradle'

buildscript {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.2'
        classpath 'robust.gradle.plugin:robust:3.0.6'
        classpath 'robust.gradle.plugin:auto-patch-plugin:1.1.8'
    }
}

allprojects {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
