import org.gradle.internal.extensibility.DefaultExtraPropertiesExtension

apply plugin: 'groovy'
apply plugin: 'maven-publish'

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation 'com.android.tools.build:gradle:4.0.2'
    implementation 'org.javassist:javassist:3.27.0-GA'
//    compile 'com.meituan.robust:autopatchbase:' + VERSION_NAME
//    implementation project(':autopatchbase')

    implementation 'com.hoolai.roubust.base:hoolai-robust-base:1.0.0'
}
//apply from: '../gradle_mvn_push.gradle'

def ext = rootProject.ext
def autoplugin = ext.autoplugin

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = autoplugin.groupId
            artifactId = autoplugin.name
            version = autoplugin.version
        }
    }
    repositories {
        maven {
            name = 'localRepo'
            url = layout.buildDirectory.dir("repo")
        }
    }
}
